import { spawn, spawnSync, type ChildProcess } from 'node:child_process';
import crypto from 'node:crypto';
import path from 'node:path';

export interface ClaudeCapabilities {
  found: boolean;
  version?: string;
  supportsStreamJson?: boolean;
  supportsPermissionPrompts?: boolean;
  supportsResume?: boolean;
  supportsSessionId?: boolean;
  needsVerbose?: boolean;
  permissionModes?: string[];
  error?: string;
}

/** Resolves how to invoke the CLI. `.js/.mjs` paths are run with the current Node (used by tests). */
export function commandFor(bin: string, args: string[]): { cmd: string; args: string[]; shell: boolean } {
  if (/\.(c|m)?js$/i.test(bin)) return { cmd: process.execPath, args: [bin, ...args], shell: false };
  if (process.platform === 'win32' && /\.(cmd|bat)$/i.test(bin)) {
    // npm-style shims require a shell on Windows. Arguments are generated by the runner (no user text).
    return { cmd: `"${bin}"`, args: args.map((a) => (/^[\w./:=-]+$/.test(a) ? a : `"${a.replace(/"/g, '""')}"`)), shell: true };
  }
  return { cmd: bin, args, shell: false };
}

function run(bin: string, args: string[]): { status: number | null; stdout: string; stderr: string; error?: Error } {
  const c = commandFor(bin, args);
  const r = spawnSync(c.cmd, c.args, { encoding: 'utf8', shell: c.shell, timeout: 20_000, windowsHide: true });
  return { status: r.status, stdout: r.stdout ?? '', stderr: r.stderr ?? '', error: r.error };
}

/** Inspects the installed CLI and checks the flags this runner relies on (version-aware). */
export function detectClaude(bin: string): ClaudeCapabilities {
  const v = run(bin, ['--version']);
  if (v.error || v.status !== 0) {
    return {
      found: false,
      error: v.error && (v.error as NodeJS.ErrnoException).code === 'ENOENT'
        ? `Claude Code CLI not found ("${bin}"). Install it (https://docs.claude.com/en/docs/claude-code/setup), run "claude" once to sign in, then restart the runner.`
        : `"${bin} --version" failed: ${(v.stderr || v.error?.message || '').slice(0, 300)}`,
    };
  }
  const help = run(bin, ['--help']);
  const text = help.stdout + help.stderr;
  const has = (flag: string) => new RegExp(`(^|\\s|,)${flag.replace(/-/g, '\\-')}(\\s|,|=|$)`, 'm').test(text);
  // The option's help block runs until the next line that starts a new option.
  const start = text.search(/^\s*--permission-mode\b/m);
  const block = start >= 0 ? text.slice(start).split(/\n\s*-{1,2}[a-zA-Z]/)[0] : '';
  const modes = /\(choices:([^)]*)\)/.exec(block)?.[1];
  const permissionModes = modes ? [...modes.matchAll(/"([^"]+)"/g)].map((m) => m[1]) : [];
  const caps: ClaudeCapabilities = {
    found: true,
    version: v.stdout.trim().split('\n')[0].slice(0, 80),
    supportsStreamJson: has('--print') && has('--output-format') && text.includes('stream-json'),
    supportsPermissionPrompts: has('--permission-prompts'),
    supportsResume: has('--resume'),
    supportsSessionId: has('--session-id'),
    needsVerbose: has('--verbose'),
    permissionModes,
  };
  if (!caps.supportsStreamJson) caps.error = 'This Claude Code version does not support "--print --output-format stream-json"; please update it.';
  else if (!has('--permission-mode')) caps.error = 'This Claude Code version does not support --permission-mode; please update it.';
  return caps;
}

const FORBIDDEN = ['--dangerously-skip-permissions', '--allow-dangerously-skip-permissions', 'bypassPermissions'];

/** Maps the app's permission choice to the installed CLI's vocabulary. Never maps to a bypass mode. */
export function mapPermissionMode(choice: string, caps: ClaudeCapabilities): string {
  const available = caps.permissionModes ?? [];
  const wanted = choice === 'default' ? (available.includes('default') ? 'default' : available.includes('manual') ? 'manual' : 'default') : choice;
  if (FORBIDDEN.includes(wanted) || wanted === 'auto') throw new Error(`Permission mode "${choice}" is not allowed by the NodePilot runner`);
  if (!['plan', 'default', 'manual', 'acceptEdits', 'dontAsk'].includes(wanted)) throw new Error(`Unknown permission mode "${choice}"`);
  if (available.length && !available.includes(wanted)) throw new Error(`The installed Claude Code CLI does not offer permission mode "${wanted}" (available: ${available.join(', ')})`);
  return wanted;
}

export interface ClaudeRunOptions {
  bin: string;
  caps: ClaudeCapabilities;
  cwd: string;
  prompt: string;
  permissionMode: string;
  allowedTools: string[];
  resumeSessionId?: string;
  addDirs?: string[];
}

/** Builds the argument list for `claude -p` in streaming JSON mode. */
export function buildArgs(o: ClaudeRunOptions): { args: string[]; sessionId: string } {
  const sessionId = o.resumeSessionId ?? crypto.randomUUID();
  const args = ['-p', '--output-format', 'stream-json'];
  if (o.caps.needsVerbose) args.push('--verbose');
  args.push('--permission-mode', mapPermissionMode(o.permissionMode, o.caps));
  // Headless: anything that would prompt is denied (and reported), rather than silently approved.
  if (o.caps.supportsPermissionPrompts) args.push('--permission-prompts', 'none');
  if (o.resumeSessionId) {
    if (!o.caps.supportsResume) throw new Error('This Claude Code version does not support --resume');
    args.push('--resume', o.resumeSessionId);
  } else if (o.caps.supportsSessionId) {
    args.push('--session-id', sessionId);
  }
  if (o.allowedTools.length) args.push('--allowedTools', o.allowedTools.join(','));
  for (const d of o.addDirs ?? []) args.push('--add-dir', d);
  assertNoBypass(args);
  return { args, sessionId };
}

export function assertNoBypass(args: string[]) {
  for (const a of args) if (FORBIDDEN.some((f) => a.includes(f))) throw new Error(`Refusing to pass permission-bypass flag "${a}"`);
}

export interface ParsedEvent {
  kind: 'system' | 'assistant' | 'tool_use' | 'tool_result' | 'permission_denied' | 'error' | 'result' | 'log';
  text: string;
  data?: unknown;
}

export interface ClaudeResult {
  sessionId?: string;
  isError: boolean;
  subtype?: string;
  resultText?: string;
  costUsd?: number;
  numTurns?: number;
  durationMs?: number;
  usage?: unknown;
  permissionDenials: unknown[];
}

const clip = (s: string, n = 2000) => (s.length > n ? s.slice(0, n) + `… [${s.length - n} more chars]` : s);

/** Converts one stream-json line into displayable events and updates the running result. */
export function parseStreamLine(line: string, acc: ClaudeResult): ParsedEvent[] {
  let msg: Record<string, unknown>;
  try {
    msg = JSON.parse(line);
  } catch {
    return line.trim() ? [{ kind: 'log', text: clip(line) }] : [];
  }
  const out: ParsedEvent[] = [];
  if (typeof msg.session_id === 'string') acc.sessionId = msg.session_id;
  switch (msg.type) {
    case 'system':
      if (msg.subtype === 'init') {
        out.push({ kind: 'system', text: `Session ${msg.session_id} started (model ${msg.model ?? '?'}, permission mode ${msg.permissionMode ?? '?'})`, data: { tools: msg.tools, cwd: msg.cwd } });
      }
      break;
    case 'assistant': {
      const content = ((msg.message as { content?: unknown[] })?.content ?? []) as Record<string, unknown>[];
      for (const c of content) {
        if (c.type === 'text' && typeof c.text === 'string' && c.text.trim()) out.push({ kind: 'assistant', text: clip(c.text, 8000) });
        if (c.type === 'tool_use') out.push({ kind: 'tool_use', text: `${c.name}: ${clip(JSON.stringify(c.input ?? {}), 600)}`, data: { id: c.id, name: c.name } });
      }
      break;
    }
    case 'user': {
      const content = ((msg.message as { content?: unknown[] })?.content ?? []) as Record<string, unknown>[];
      for (const c of content) {
        if (c.type !== 'tool_result') continue;
        const text = typeof c.content === 'string' ? c.content : JSON.stringify(c.content ?? '');
        out.push({ kind: c.is_error ? 'error' : 'tool_result', text: clip(text, 1500), data: { toolUseId: c.tool_use_id } });
      }
      break;
    }
    case 'result': {
      acc.isError = !!msg.is_error || (typeof msg.subtype === 'string' && msg.subtype !== 'success');
      acc.subtype = msg.subtype as string;
      acc.resultText = typeof msg.result === 'string' ? msg.result : undefined;
      acc.costUsd = typeof msg.total_cost_usd === 'number' ? msg.total_cost_usd : undefined;
      acc.numTurns = msg.num_turns as number | undefined;
      acc.durationMs = msg.duration_ms as number | undefined;
      acc.usage = msg.usage;
      acc.permissionDenials = Array.isArray(msg.permission_denials) ? msg.permission_denials : [];
      for (const d of acc.permissionDenials as { tool_name?: string; tool_input?: unknown }[]) {
        out.push({ kind: 'permission_denied', text: `Permission denied: ${d.tool_name ?? 'tool'} ${clip(JSON.stringify(d.tool_input ?? {}), 400)}`, data: d });
      }
      out.push({ kind: 'result', text: `${acc.isError ? 'Claude finished with an error' : 'Claude finished'} (${msg.subtype ?? 'unknown'})${acc.resultText ? `: ${clip(acc.resultText, 4000)}` : ''}` });
      break;
    }
    default:
      break;
  }
  return out;
}

export function spawnClaude(o: ClaudeRunOptions, args: string[]): ChildProcess {
  const c = commandFor(o.bin, args);
  const child = spawn(c.cmd, c.args, {
    cwd: o.cwd,
    shell: c.shell,
    windowsHide: true,
    detached: process.platform !== 'win32', // own process group so cancellation kills children too
    stdio: ['pipe', 'pipe', 'pipe'],
    // Credentials stay with the CLI's normal local auth; the runner neither reads nor forwards them.
    env: process.env,
  });
  child.stdin!.end(o.prompt);
  return child;
}

export function killTree(child: ChildProcess) {
  if (child.exitCode !== null || !child.pid) return;
  if (process.platform === 'win32') {
    spawnSync('taskkill', ['/pid', String(child.pid), '/T', '/F'], { windowsHide: true });
  } else {
    try {
      process.kill(-child.pid, 'SIGTERM');
    } catch {
      child.kill('SIGTERM');
    }
    setTimeout(() => {
      try { process.kill(-child.pid!, 'SIGKILL'); } catch { /* already gone */ }
    }, 5000).unref();
  }
}

export const isPathInside = (root: string, p: string) => {
  const rel = path.relative(root, p);
  return rel === '' || (!rel.startsWith('..') && !path.isAbsolute(rel));
};
